Fix build with lemon-3.44
:Release Notes:
Fixed build error after lemon tool upgraded to 3.44

:Detailed Notes:
Update the syntax in %syntax_error function to work with newer lemon

The yy_syntax_error() function is updated from this commit:
https://github.com/sqlite/sqlite/commit/45f31be85dc90a3f76dd930ad4ec2a0174105156#diff-4ac00843d55028f60091f7ed92753bd216a0eaddd37723d8164ae7f85588e8a8L704

This caused an error:
selectors_grammar_y.y: In function 'yy_syntax_error':
selectors_grammar_y.y:47:17: error: 'raw_buffer' has no member named
'yy0'
selectors_grammar_y.y:56:37: error: 'raw_buffer' has no member named
'yy0'

Use TOKEN macro to support both version.

:Testing Performed:
Only build tested

:QA Notes:

:Issues Addressed:
[WRQ-6118] check webosose github issue "pbnjson fails to build #27"

Change-Id: I0d9599a6bbc041f6d778a663c7ac569f111c9542