Fix build paths issue in libpbnjson
:Release Notes:
Fix for QA warning for build path.
Striping of lines in auto-generated files and
addition of support for lemon extra arguments

:Detailed Notes:
* use -L to avoid full paths in line control directives:
  libpbnjson-native/2.15.0-16/git $ grep tmp-glibc 
../build/src/pbnjson_c/selectors/seleectors_grammar_l.c

  #line 1 "/OE/build/luneos-styhead/tmp-glibc/work/x86_64-linux/libpbnjson-native/2.15.0-16/
build/src/pbnjson_c/selectors/seletors_grammar_l.c"c
  #line 3 "/OE/build/luneos-styhead/tmp-glibc/work/x86_64-linux/libpbnjson-native/2.15.0-16/
build/src/pbnjson_c/selectors/selectors_grammar_l.c"

* as detected by buildpaths QA check:

ERROR: libpbnjson-clang-2.15.0-16-r5 do_package_qa: QA Issue: File /usr/src/debug/
libpbnjson-clang/2.15.0-16/src/pbnjson_c/selectors/selectors_grammar_l.c 
in package libpbnjson-clang-src contains reference to TMPDIR

ERROR: libpbnjson-2.15.0-16-r17 do_package_qa: QA Issue: File /usr/src/debug/libpbnjson/
2.15.0-16/src/pbnjson_c/selectors/selectors_grammar_l.c
in package libpbnjson-src contains reference to TMPDIR



lemon supports -l since 2008:
https://github.com/sqlite/sqlite/commit/5854393cd9d3ca956669673ff249ef999f75c056

even the lemon from sqlite 3.7.3 used before the upgrade in:
https://git.openembedded.org/meta-openembedded/commit/
?id=c3ac5cf180f960dbbf6e3a3e76d6d44094873c72
did support -l

So not sure why -l<file> was added to apply_lemon.sh in 2015 with:
https://g2g.lgsvl.com/7102 Add support for lemon extra arguments
  http://gpro.lge.com/gitweb?p=webos/libpbnjson.git;a=commit;
  h=78331aab6435b41fd3d133fa92c66accdb95eecd
https://g2g.lgsvl.com/7181 Strip #line from autogenerated file
  http://gpro.lge.com/gitweb?p=webos/libpbnjson.git;a=commit;
  h=d455a73f29affda4290aad833ff5616ab043a1a5

instead of just adding -l to lemon call.

The sed worked but we should also call lemon with relative path to grammar file, because
it also generates the buildpath as "source file" in comment as:

** source file "/OE/build/luneos-styhead/tmp-glibc/work/corei7-64-webos-linux/libpbnjson/
2.15.0-16/build/src/pbnjson_c/validation/json_schema_grammar.y".

Added in 2020 sqlite 3.45.1:
https://github.com/sqlite/sqlite/commit/512aa78ca28981229858e0fd98aaba1158b6e8af

and it's still in latest sqlite:
https://github.com/sqlite/sqlite/commit/4fa5952090ad974d6a11952267662d4af338154a#
diff-633c611978778713c1360ca3046e277e54c6a7569108c74b3300da07133d1933R4412
without easy way to strip the path.

Fixes:
ERROR: libpbnjson-2.15.0-16-r17 do_package_qa: QA Issue: File /usr/src/debug/libpbnjson/
2.15.0-16/src/pbnjson_c/validation/json_schema_grammar.c
in package libpbnjson-src contains reference to TMPDIR [buildpaths]

:Testing Performed:
Locally Tested.

:QA Notes:
NA

:Issues Addressed:
[WRP-10884] libpbnjson: Resolve buildpaths QA warnings

Change-Id: I517d8f79887240233f94456ca29c8b8b4ded0bd3